package bandclient

/*
	type AutoGenerated struct {
		Text        string `json:"text"`
		Attachments []struct {
			Title  string `json:"title"`
			Color  string `json:"color"`
			Fields []struct {
				Title string `json:"title"`
				Value string `json:"value"`
				Short bool   `json:"short"`
			} `json:"fields"`
			Footer string `json:"footer"`
			Ts     int    `json:"ts"`
		} `json:"attachments"`
		Priority struct {
			Priority     string `json:"priority"`
			RequestedAck bool   `json:"requested_ack"`
		} `json:"priority"`
	}
*/
const (
	errColor Color = "#FF0000"
	okColor  Color = "#008000"
	footer         = "System Alert"
)

type Color string

type Message struct {
	Text        string       `json:"text"`
	Attachments []Attachment `json:"attachments"`
	Priority    Priority     `json:"priority"`
}

type TextLine struct {
	Text string `json:"text"`
}

func (m *Message) SetLevel(level string) {
	m.Priority.Priority = level
}

type Attachment struct {
	Color  Color   `json:"color"`
	Title  string  `json:"title"`
	Fields []Field `json:"fields"`
	Footer string  `json:"footer"`
	TS     int     `json:"ts"`
}

type Field struct {
	Title string `json:"title"`
	Value string `json:"value"`
	Short bool   `json:"short"`
}

func NewField(title, value string, short bool) Field {
	return Field{
		Title: title,
		Value: value,
		Short: short,
	}
}

type Priority struct {
	Priority     string `json:"priority"`
	RequestedAck bool   `json:"requested_ack"`
}

func NewPriority(priority string) Priority {
	return Priority{
		Priority:     priority,
		RequestedAck: true,
	}
}

const defaultLevel = "urgent"

func NewOKMsg(text, status, handler, cluster, time, responseBody string) *Message {
	return &Message{
		Text: text,
		Attachments: []Attachment{
			{
				Title: "#### :check-neon: **Status OK** :check-neon:",
				Color: okColor,
				Fields: []Field{
					NewField("Status", status, true),
					NewField("Response Body", responseBody, true),
					NewField("Handler", handler, true),
					NewField("Cluster", cluster, true),
					NewField("Time", time, false),
				},
				Footer: footer,
				TS:     171758643,
			},
		},
		Priority: NewPriority(defaultLevel),
	}
}

func NewErrMsg(text, status, handler, cluster, time, responseBody string) *Message {
	return &Message{
		Text: text,
		Attachments: []Attachment{
			{
				Title: "#### :rotating_light: **ALERT ERROR** :rotating_light:",
				Color: errColor,
				Fields: []Field{
					NewField("Status", status, true),
					NewField("Response Body", responseBody, true),
					NewField("Handler", handler, true),
					NewField("Cluster", cluster, true),
					NewField("Time", time, false),
				},
				Footer: footer,
				TS:     171758643,
			},
		},
		Priority: NewPriority(defaultLevel),
	}
}
